### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/cbor#1]
What is the license of this code?

**Comment by whyrusleeping** [comment]
thats...  a good question.

**Comment by whyrusleeping** [comment]
https://bitbucket.org/bodhisnarkva/cbor/issues/3/license-copying-file

**Comment by jbenet** [comment]
update: @whyrusleeping had reached out to the author-- hopefully author will license work permissively.

**Comment by jbenet** [comment]
@whyrusleeping you may want to ask author to license as BSD, MIT, Apache2, or similar. (IPFS cannot use GPL)

**Comment by jbenet** [comment]
https://bitbucket.org/bodhisnarkva/cbor/src/97648173ddcfac85928be2b9139e82ef0af4e254/LICENSE?at=default
